#Config_ID in ConfigMaster defined:
#-input of harry plotter config      #key for the harry potter config

-2:
- "/net/scratch_cms3b/brunner/artus/AllSamples/merged/"                                                         #"input_dir"
- ["pdf", "png"]                                                                                                #"formats"
- True                                                                                                          #"www_nodate"
- True                                                                                                          #"cms_outframe"
- "Work in progress"                                                                                            #"extra_text"

-1:
- null                               #category
- "new"                              #estimation method
- "baseline"                              #cut type

0:
- [0.65, 0.55, 1.0, 0.85]            #"legend"
- [35.87]                            #"lumis"
- [13]                               #"energies"
- "2016"                             #"year"
- "Plots"                            #"www"

1:
- "CutEfficiency"                    #"analysis_modules"
- ["L"]                              #"markers"
- "S/#sqrt{S+B}"                     #"y_label"
- ["sOverSqrtSB"]                    #"cut_efficiency_modes"
- ["sOverSqrtSB"]                    #"cut_efficiency_nicks"
- ["sOverSqrtSB"]                    #"nicks_whitelist"
- null                               #"legend"
- [35.87]                            #"lumis"
- [13]                               #"energies
- "2016"                             #"year"
- "CutEfficiency"                    #"www"

2:
- "arb. units"                       #"y_label"
- "NormalizeToUnity"                 #"analysis_modules"
- [0.65, 0.65, 1.00, 0.88]           #"legend"
- [35.87]                            #"lumis"
- [13]                               #"energies
- "2016"                             #"year"
- "ShapePlot"                        #"www"

4:
- [0.67, 0.70, 0.92, 0.88]           #"legend"
- [35.87]                            #"lumis"
- [13]                               #"energies
- "2016"                             #"year"
- "Nminus1Plot"                      #"www"

5:
- ["soverb"]                         #"subplot_nicks"
- "S/#sqrt{S+B}"                     #"y_subplot_label"
- [0.75, 0.60, 1, 0.83]              #"legend"
- [35.87]                            #"lumis"
- [13]                               #"energies
- "2016"                             #"year"
- "Cutflow"                          #"www"

6:
- "95% CL Limit on BR(Z#rightarrowLFV)"                                                                                                                  #"y_label"
- ["limit"]                                                                                                                                              #"folders"
- ["limit_exp:limit_exp-two_sigma_down:two_sigma_up-limit_exp", "limit_exp:limit_exp-one_sigma_down:one_sigma_up-limit_exp", "limit_exp:0:0", "limit_old:0:0", "limit_obs:0:0"]                                                                                                                                          #"y_expressions"
- ["E5", "E5", "P", "P", "P"]                                                                                                                            #"markers"
- ["kYellow", "kGreen", "kBlack", "kBlack", "kBlack"]                                                                                                    #"colors
- [20, 20, 20, 21, 22]                                                                                                                                   #"marker_styles"
- [40, 40, 1, 1, 1]                                                                                                                                      #"line_widths"
- ["TGraphAsymmErrorsY", "TGraphAsymmErrorsY", "TGraphAsymmErrorsY", "TGraphAsymmErrorsY", "TGraphAsymmErrorsY"]                                         #"tree_draw_options"
- ["95% expected", "68% expected", "Expected", "Old observed limit", "Observed"]                                                                         #"nicks"
- [-0.5, 2.5]                                                                                                                                            #"x_lims"
- [0.0, 0.0000016]                                                                                                                                                  #"y_lims"
- ["1 jet", "0 jet", "combined"]                                                                                                                         #"x_ticks_label"
- [0.65, 0.65, 0.95, 0.88]
- [35.87]
- [13]
- "2016"
- "Limits"
